sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO='Django>=1.4,<1.5' SKIP='3.3 3.4 3.5'
  - DJANGO='Django>=1.5,<1.6' SKIP='3.3 3.4 3.5'
  - DJANGO='Django>=1.6,<1.7' SKIP='3.4 3.5'
  - DJANGO='Django>=1.7,<1.8' SKIP='2.6'
  - DJANGO='Django>=1.8,<1.9' SKIP='2.6'
install:
  scripts/travis-install.sh
script:
  scripts/travis-build.sh
after_success:
  coveralls
