language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install --use-mirrors -r test_requirements.txt"
  - "pip install --use-mirrors https://github.com/landscapeio/pylint-plugin-utils"
  - "pip install --use-mirrors --editable ."
script: python test/test_func.py
