sudo: false
language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "3.5"
env:
  - DJANGO='Django>=1.7,<1.8' SKIP='2.6 3.5'
  - DJANGO='Django>=1.8,<1.9' SKIP='2.6'
  - DJANGO='Django>=1.9,<1.10' SKIP='2.6 3.3'
  - DJANGO='Django>=1.10,<1.11' SKIP='2.6 3.3'
install:
  scripts/travis-install.sh
script:
  scripts/travis-build.sh
after_success:
  coveralls
