language: python
python:
  - 3.5
  - 3.6
  - "3.7-dev"
env:
  # note: latest versions first b/c the top-most is included in new
  # build stages if not specified
  - DJANGO=2.1
stages:
  - django_not_installed
  - django_is_installed
  - test
  - build_and_package_sanity
matrix:
  include:
    - { stage: django_not_installed, python: 3.6, env: TOXENV=django_not_installed }
    - { stage: django_is_installed, python: 3.6, env: TOXENV=django_is_installed }
    - { stage: test, python: 3.6, env: DJANGO=2.0 }
    - { stage: test, python: 3.6, env: DJANGO=1.11 }
    - { stage: test, python: 3.6, env: TOXENV=flake8 }
    - { stage: test, python: 3.6, env: TOXENV=pylint }
    - { stage: test, python: 3.6, env: TOXENV=readme }
    - { stage: build_and_package_sanity, python: 3.6, env: SANITY_CHECK=1 }
  allow_failures:
    - env: TOXENV=pylint

install:
  - pip install tox-travis
script:
  - |
        if [ -z "$SANITY_CHECK" ]; then
            tox
        else
            ./scripts/build.sh
        fi

after_success:
  - |
        if [ -z "$SANITY_CHECK" ]; then
            pip install coveralls
            coveralls
        fi

notifications:
  email:
    on_failure: change
    on_success: never
