language: python
python:
  - "2.6"
  - "2.7"
install:
  - "pip install --use-mirrors coverage coveralls"
  - "pip install --use-mirrors -r test_requirements.txt"
  - "pip install --use-mirrors git+https://github.com/landscapeio/pylint-plugin-utils.git@develop"
  - "pip install --use-mirrors --editable ."
script:
  coverage run test/test_func.py
after_success:
  coveralls
